//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvantechDebug {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class CanSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static CanSettings defaultInstance = ((CanSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CanSettings())));
        
        public static CanSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public int BpNumbers {
            get {
                return ((int)(this["BpNumbers"]));
            }
            set {
                this["BpNumbers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int StringNumbers {
            get {
                return ((int)(this["StringNumbers"]));
            }
            set {
                this["StringNumbers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("can1")]
        public string CANPort {
            get {
                return ((string)(this["CANPort"]));
            }
            set {
                this["CANPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("125")]
        public string CANBaudrate {
            get {
                return ((string)(this["CANBaudrate"]));
            }
            set {
                this["CANBaudrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Single")]
        public string CanAcceptanceFilterMode {
            get {
                return ((string)(this["CanAcceptanceFilterMode"]));
            }
            set {
                this["CanAcceptanceFilterMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FFFFFFFF")]
        public string CanAcceptanceMask {
            get {
                return ((string)(this["CanAcceptanceMask"]));
            }
            set {
                this["CanAcceptanceMask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FFFFFFFF")]
        public string CanAcceptanceCode {
            get {
                return ((string)(this["CanAcceptanceCode"]));
            }
            set {
                this["CanAcceptanceCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public string CanWriteTimeOut {
            get {
                return ((string)(this["CanWriteTimeOut"]));
            }
            set {
                this["CanWriteTimeOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public string CanReadTimeOut {
            get {
                return ((string)(this["CanReadTimeOut"]));
            }
            set {
                this["CanReadTimeOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string CanMaxMsgCount {
            get {
                return ((string)(this["CanMaxMsgCount"]));
            }
            set {
                this["CanMaxMsgCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int CellNumbers {
            get {
                return ((int)(this["CellNumbers"]));
            }
            set {
                this["CellNumbers"] = value;
            }
        }
    }
}
